POST http://localhost:3000/userChangePassword HTTP/1.1
Content-Type: application/json

{"input" : {"user_name" : "Nandar", "oldPassword" : "pass", "newPassword" : "11111"}}

###
POST http://localhost:3000/adminChangePassword HTTP/1.1
Content-Type: application/json

{"input" : {"user_name" : "admin", "oldPassword" : "pass", "newPassword" : "11111"}}
